version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - land_network

  app:
    build: .
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "10001:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - land_network

  nginx:
    image: nginx:latest
    ports:
      - "10002:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - land_network

networks:
  land_network:

volumes:
  postgres_data:
  static_volume:
  media_volume:
