# Generated by Django 5.1.6 on 2025-02-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cards/', verbose_name='Изображение карточки')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок карточки')),
                ('text', models.TextField(verbose_name='Текст карточки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Карточка «Почему выбирают нас?»',
                'verbose_name_plural': 'Карточки «Почему выбирают нас?»',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='slider_images/', verbose_name='Изображение слайдера'),
        ),
    ]
