# Generated by Django 5.1.6 on 2025-02-23 10:03

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_whychoosecard_alter_sliderimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychoosecard',
            name='image',
            field=models.FileField(upload_to='cards/', validators=[home.models.validate_image_or_svg], verbose_name='Изображение карточки'),
        ),
    ]
